//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CAppMvc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2CCharm.onmicrosoft.com")]
        public string B2CTenant {
            get {
                return ((string)(this["B2CTenant"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>b2c_1_wingtiptoyssignup</string>
  <string>b2c_1_passwordreset</string>
  <string>b2c_1_profileediting</string>
  <string>b2c_1a_signupwithrest</string>
  <string>b2c_1a_signupwithrestandidp</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection B2CPolicy {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["B2CPolicy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.microsoftonline.com/{0}/v2.0/.well-known/openid-configuration?p={1}" +
            "")]
        public string B2CMetadata {
            get {
                return ((string)(this["B2CMetadata"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7393f3b7-7c95-490e-b854-5cae8b7d160a")]
        public string B2CClientId {
            get {
                return ((string)(this["B2CClientId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Irb!S)7O9{s#3U{5")]
        public string B2CClientSecret {
            get {
                return ((string)(this["B2CClientSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://b2cappmvc.azurewebsites.net/")]
        public string AppRedirectUri {
            get {
                return ((string)(this["AppRedirectUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wingtip Toys")]
        public string AppName {
            get {
                return ((string)(this["AppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>A basic sign-up or sign-in policy for local, Facebook, Google, and Microsoft accounts</string>
  <string>(Hidden) A basic password reset policy for a local account</string>
  <string>(Hidden) A basic profile editing policy for local, Facebook, Google, and Microsoft accounts</string>
  <string>An advanced sign-up or sign-in policy that integrates with a REST API</string>
  <string>An advanced sign-up or sign-in policy that integrates with a custom identity provider</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Caption {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Caption"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"ClaimType\":\"Loyalty\",\"ClaimValue\":\"LXXXXXX\",\"Policy\":\"B2C_1A_SignupWithRest\"}")]
        public string AddClientClaimsToPolicy {
            get {
                return ((string)(this["AddClientClaimsToPolicy"]));
            }
        }
    }
}
